/*
 * This file is generated by jOOQ.
 */
package jooq.steve.db2.tables.records;


import jooq.steve.db2.tables.LiveTransactionDetails;

import org.joda.time.DateTime;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LiveTransactionDetailsRecord extends TableRecordImpl<LiveTransactionDetailsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>ev_history.live_transaction_details.transaction_id</code>.
     */
    public LiveTransactionDetailsRecord setTransactionId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.live_transaction_details.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ev_history.live_transaction_details.id_tag</code>.
     */
    public LiveTransactionDetailsRecord setIdTag(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ev_history.live_transaction_details.id_tag</code>.
     */
    public String getIdTag() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ev_history.live_transaction_details.start_energy</code>.
     */
    public LiveTransactionDetailsRecord setStartEnergy(Double value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ev_history.live_transaction_details.start_energy</code>.
     */
    public Double getStartEnergy() {
        return (Double) get(2);
    }

    /**
     * Setter for
     * <code>ev_history.live_transaction_details.tariff_amount</code>.
     */
    public LiveTransactionDetailsRecord setTariffAmount(Double value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.live_transaction_details.tariff_amount</code>.
     */
    public Double getTariffAmount() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>ev_history.live_transaction_details.last_energy</code>.
     */
    public LiveTransactionDetailsRecord setLastEnergy(Double value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ev_history.live_transaction_details.last_energy</code>.
     */
    public Double getLastEnergy() {
        return (Double) get(4);
    }

    /**
     * Setter for
     * <code>ev_history.live_transaction_details.wallet_amount</code>.
     */
    public LiveTransactionDetailsRecord setWalletAmount(Double value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.live_transaction_details.wallet_amount</code>.
     */
    public Double getWalletAmount() {
        return (Double) get(5);
    }

    /**
     * Setter for
     * <code>ev_history.live_transaction_details.consumed_energy</code>.
     */
    public LiveTransactionDetailsRecord setConsumedEnergy(Double value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.live_transaction_details.consumed_energy</code>.
     */
    public Double getConsumedEnergy() {
        return (Double) get(6);
    }

    /**
     * Setter for
     * <code>ev_history.live_transaction_details.consumed_amount</code>.
     */
    public LiveTransactionDetailsRecord setConsumedAmount(Double value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.live_transaction_details.consumed_amount</code>.
     */
    public Double getConsumedAmount() {
        return (Double) get(7);
    }

    /**
     * Setter for
     * <code>ev_history.live_transaction_details.total_consumed_amount</code>.
     */
    public LiveTransactionDetailsRecord setTotalConsumedAmount(Double value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.live_transaction_details.total_consumed_amount</code>.
     */
    public Double getTotalConsumedAmount() {
        return (Double) get(8);
    }

    /**
     * Setter for
     * <code>ev_history.live_transaction_details.start_timestamp</code>.
     */
    public LiveTransactionDetailsRecord setStartTimestamp(DateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.live_transaction_details.start_timestamp</code>.
     */
    public DateTime getStartTimestamp() {
        return (DateTime) get(9);
    }

    /**
     * Setter for
     * <code>ev_history.live_transaction_details.stop_timestamp</code>.
     */
    public LiveTransactionDetailsRecord setStopTimestamp(DateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.live_transaction_details.stop_timestamp</code>.
     */
    public DateTime getStopTimestamp() {
        return (DateTime) get(10);
    }

    /**
     * Setter for
     * <code>ev_history.live_transaction_details.is_active_transaction</code>.
     */
    public LiveTransactionDetailsRecord setIsActiveTransaction(Boolean value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.live_transaction_details.is_active_transaction</code>.
     */
    public Boolean getIsActiveTransaction() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>ev_history.live_transaction_details.latest_soc</code>.
     */
    public LiveTransactionDetailsRecord setLatestSoc(Double value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>ev_history.live_transaction_details.latest_soc</code>.
     */
    public Double getLatestSoc() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>ev_history.live_transaction_details.last_power</code>.
     */
    public LiveTransactionDetailsRecord setLastPower(Double value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>ev_history.live_transaction_details.last_power</code>.
     */
    public Double getLastPower() {
        return (Double) get(13);
    }

    /**
     * Setter for <code>ev_history.live_transaction_details.last_current</code>.
     */
    public LiveTransactionDetailsRecord setLastCurrent(Double value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>ev_history.live_transaction_details.last_current</code>.
     */
    public Double getLastCurrent() {
        return (Double) get(14);
    }

    /**
     * Setter for <code>ev_history.live_transaction_details.last_voltage</code>.
     */
    public LiveTransactionDetailsRecord setLastVoltage(Double value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>ev_history.live_transaction_details.last_voltage</code>.
     */
    public Double getLastVoltage() {
        return (Double) get(15);
    }

    /**
     * Setter for
     * <code>ev_history.live_transaction_details.last_energy_value</code>.
     */
    public LiveTransactionDetailsRecord setLastEnergyValue(Double value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.live_transaction_details.last_energy_value</code>.
     */
    public Double getLastEnergyValue() {
        return (Double) get(16);
    }

    /**
     * Setter for
     * <code>ev_history.live_transaction_details.charge_box_id</code>.
     */
    public LiveTransactionDetailsRecord setChargeBoxId(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.live_transaction_details.charge_box_id</code>.
     */
    public String getChargeBoxId() {
        return (String) get(17);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LiveTransactionDetailsRecord
     */
    public LiveTransactionDetailsRecord() {
        super(LiveTransactionDetails.LIVE_TRANSACTION_DETAILS);
    }

    /**
     * Create a detached, initialised LiveTransactionDetailsRecord
     */
    public LiveTransactionDetailsRecord(Integer transactionId, String idTag, Double startEnergy, Double tariffAmount, Double lastEnergy, Double walletAmount, Double consumedEnergy, Double consumedAmount, Double totalConsumedAmount, DateTime startTimestamp, DateTime stopTimestamp, Boolean isActiveTransaction, Double latestSoc, Double lastPower, Double lastCurrent, Double lastVoltage, Double lastEnergyValue, String chargeBoxId) {
        super(LiveTransactionDetails.LIVE_TRANSACTION_DETAILS);

        setTransactionId(transactionId);
        setIdTag(idTag);
        setStartEnergy(startEnergy);
        setTariffAmount(tariffAmount);
        setLastEnergy(lastEnergy);
        setWalletAmount(walletAmount);
        setConsumedEnergy(consumedEnergy);
        setConsumedAmount(consumedAmount);
        setTotalConsumedAmount(totalConsumedAmount);
        setStartTimestamp(startTimestamp);
        setStopTimestamp(stopTimestamp);
        setIsActiveTransaction(isActiveTransaction);
        setLatestSoc(latestSoc);
        setLastPower(lastPower);
        setLastCurrent(lastCurrent);
        setLastVoltage(lastVoltage);
        setLastEnergyValue(lastEnergyValue);
        setChargeBoxId(chargeBoxId);
        resetChangedOnNotNull();
    }
}
