/*
 * This file is generated by jOOQ.
 */
package jooq.steve.db2.tables.records;


import jooq.steve.db2.tables.WalletTrackSettlementNew;

import org.joda.time.DateTime;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WalletTrackSettlementNewRecord extends UpdatableRecordImpl<WalletTrackSettlementNewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ev_history.wallet_track_settlement_new.id</code>.
     */
    public WalletTrackSettlementNewRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ev_history.wallet_track_settlement_new.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>ev_history.wallet_track_settlement_new.transaction_id</code>.
     */
    public WalletTrackSettlementNewRecord setTransactionId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.wallet_track_settlement_new.transaction_id</code>.
     */
    public Integer getTransactionId() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>ev_history.wallet_track_settlement_new.station_id</code>.
     */
    public WalletTrackSettlementNewRecord setStationId(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.wallet_track_settlement_new.station_id</code>.
     */
    public String getStationId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ev_history.wallet_track_settlement_new.cpo_id</code>.
     */
    public WalletTrackSettlementNewRecord setCpoId(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>ev_history.wallet_track_settlement_new.cpo_id</code>.
     */
    public String getCpoId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ev_history.wallet_track_settlement_new.id_tag</code>.
     */
    public WalletTrackSettlementNewRecord setIdTag(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>ev_history.wallet_track_settlement_new.id_tag</code>.
     */
    public String getIdTag() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>ev_history.wallet_track_settlement_new.start_energy</code>.
     */
    public WalletTrackSettlementNewRecord setStartEnergy(Double value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.wallet_track_settlement_new.start_energy</code>.
     */
    public Double getStartEnergy() {
        return (Double) get(5);
    }

    /**
     * Setter for
     * <code>ev_history.wallet_track_settlement_new.tariff_amount</code>.
     */
    public WalletTrackSettlementNewRecord setTariffAmount(Double value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.wallet_track_settlement_new.tariff_amount</code>.
     */
    public Double getTariffAmount() {
        return (Double) get(6);
    }

    /**
     * Setter for
     * <code>ev_history.wallet_track_settlement_new.last_energy</code>.
     */
    public WalletTrackSettlementNewRecord setLastEnergy(Double value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.wallet_track_settlement_new.last_energy</code>.
     */
    public Double getLastEnergy() {
        return (Double) get(7);
    }

    /**
     * Setter for
     * <code>ev_history.wallet_track_settlement_new.wallet_amount</code>.
     */
    public WalletTrackSettlementNewRecord setWalletAmount(Double value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.wallet_track_settlement_new.wallet_amount</code>.
     */
    public Double getWalletAmount() {
        return (Double) get(8);
    }

    /**
     * Setter for
     * <code>ev_history.wallet_track_settlement_new.consumed_energy</code>.
     */
    public WalletTrackSettlementNewRecord setConsumedEnergy(Double value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.wallet_track_settlement_new.consumed_energy</code>.
     */
    public Double getConsumedEnergy() {
        return (Double) get(9);
    }

    /**
     * Setter for
     * <code>ev_history.wallet_track_settlement_new.consumed_amount</code>.
     */
    public WalletTrackSettlementNewRecord setConsumedAmount(Double value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.wallet_track_settlement_new.consumed_amount</code>.
     */
    public Double getConsumedAmount() {
        return (Double) get(10);
    }

    /**
     * Setter for
     * <code>ev_history.wallet_track_settlement_new.total_consumed_amount</code>.
     */
    public WalletTrackSettlementNewRecord setTotalConsumedAmount(Double value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.wallet_track_settlement_new.total_consumed_amount</code>.
     */
    public Double getTotalConsumedAmount() {
        return (Double) get(11);
    }

    /**
     * Setter for
     * <code>ev_history.wallet_track_settlement_new.start_timestamp</code>.
     */
    public WalletTrackSettlementNewRecord setStartTimestamp(DateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.wallet_track_settlement_new.start_timestamp</code>.
     */
    public DateTime getStartTimestamp() {
        return (DateTime) get(12);
    }

    /**
     * Setter for
     * <code>ev_history.wallet_track_settlement_new.stop_timestamp</code>.
     */
    public WalletTrackSettlementNewRecord setStopTimestamp(DateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.wallet_track_settlement_new.stop_timestamp</code>.
     */
    public DateTime getStopTimestamp() {
        return (DateTime) get(13);
    }

    /**
     * Setter for
     * <code>ev_history.wallet_track_settlement_new.is_active_transaction</code>.
     */
    public WalletTrackSettlementNewRecord setIsActiveTransaction(Boolean value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.wallet_track_settlement_new.is_active_transaction</code>.
     */
    public Boolean getIsActiveTransaction() {
        return (Boolean) get(14);
    }

    /**
     * Setter for
     * <code>ev_history.wallet_track_settlement_new.dealer_unit_cost</code>.
     */
    public WalletTrackSettlementNewRecord setDealerUnitCost(Double value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.wallet_track_settlement_new.dealer_unit_cost</code>.
     */
    public Double getDealerUnitCost() {
        return (Double) get(15);
    }

    /**
     * Setter for
     * <code>ev_history.wallet_track_settlement_new.dealer_total_amount</code>.
     */
    public WalletTrackSettlementNewRecord setDealerTotalAmount(Double value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.wallet_track_settlement_new.dealer_total_amount</code>.
     */
    public Double getDealerTotalAmount() {
        return (Double) get(16);
    }

    /**
     * Setter for
     * <code>ev_history.wallet_track_settlement_new.customer_share_amount</code>.
     */
    public WalletTrackSettlementNewRecord setCustomerShareAmount(Double value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.wallet_track_settlement_new.customer_share_amount</code>.
     */
    public Double getCustomerShareAmount() {
        return (Double) get(17);
    }

    /**
     * Setter for
     * <code>ev_history.wallet_track_settlement_new.total_share_amount</code>.
     */
    public WalletTrackSettlementNewRecord setTotalShareAmount(Double value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for
     * <code>ev_history.wallet_track_settlement_new.total_share_amount</code>.
     */
    public Double getTotalShareAmount() {
        return (Double) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WalletTrackSettlementNewRecord
     */
    public WalletTrackSettlementNewRecord() {
        super(WalletTrackSettlementNew.WALLET_TRACK_SETTLEMENT_NEW);
    }

    /**
     * Create a detached, initialised WalletTrackSettlementNewRecord
     */
    public WalletTrackSettlementNewRecord(Integer id, Integer transactionId, String stationId, String cpoId, String idTag, Double startEnergy, Double tariffAmount, Double lastEnergy, Double walletAmount, Double consumedEnergy, Double consumedAmount, Double totalConsumedAmount, DateTime startTimestamp, DateTime stopTimestamp, Boolean isActiveTransaction, Double dealerUnitCost, Double dealerTotalAmount, Double customerShareAmount, Double totalShareAmount) {
        super(WalletTrackSettlementNew.WALLET_TRACK_SETTLEMENT_NEW);

        setId(id);
        setTransactionId(transactionId);
        setStationId(stationId);
        setCpoId(cpoId);
        setIdTag(idTag);
        setStartEnergy(startEnergy);
        setTariffAmount(tariffAmount);
        setLastEnergy(lastEnergy);
        setWalletAmount(walletAmount);
        setConsumedEnergy(consumedEnergy);
        setConsumedAmount(consumedAmount);
        setTotalConsumedAmount(totalConsumedAmount);
        setStartTimestamp(startTimestamp);
        setStopTimestamp(stopTimestamp);
        setIsActiveTransaction(isActiveTransaction);
        setDealerUnitCost(dealerUnitCost);
        setDealerTotalAmount(dealerTotalAmount);
        setCustomerShareAmount(customerShareAmount);
        setTotalShareAmount(totalShareAmount);
        resetChangedOnNotNull();
    }
}
