/*
 * This file is generated by jOOQ.
 */
package jooq.steve.db2.tables;


import de.rwth.idsg.steve.utils.DateTimeConverter;

import java.util.Collection;

import jooq.steve.db2.EvHistory;
import jooq.steve.db2.Keys;
import jooq.steve.db2.tables.records.WalletTrackSettlementNewRecord;

import org.joda.time.DateTime;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WalletTrackSettlementNew extends TableImpl<WalletTrackSettlementNewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>ev_history.wallet_track_settlement_new</code>
     */
    public static final WalletTrackSettlementNew WALLET_TRACK_SETTLEMENT_NEW = new WalletTrackSettlementNew();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WalletTrackSettlementNewRecord> getRecordType() {
        return WalletTrackSettlementNewRecord.class;
    }

    /**
     * The column <code>ev_history.wallet_track_settlement_new.id</code>.
     */
    public final TableField<WalletTrackSettlementNewRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>ev_history.wallet_track_settlement_new.transaction_id</code>.
     */
    public final TableField<WalletTrackSettlementNewRecord, Integer> TRANSACTION_ID = createField(DSL.name("transaction_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column
     * <code>ev_history.wallet_track_settlement_new.station_id</code>.
     */
    public final TableField<WalletTrackSettlementNewRecord, String> STATION_ID = createField(DSL.name("station_id"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>ev_history.wallet_track_settlement_new.cpo_id</code>.
     */
    public final TableField<WalletTrackSettlementNewRecord, String> CPO_ID = createField(DSL.name("cpo_id"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>ev_history.wallet_track_settlement_new.id_tag</code>.
     */
    public final TableField<WalletTrackSettlementNewRecord, String> ID_TAG = createField(DSL.name("id_tag"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column
     * <code>ev_history.wallet_track_settlement_new.start_energy</code>.
     */
    public final TableField<WalletTrackSettlementNewRecord, Double> START_ENERGY = createField(DSL.name("start_energy"), SQLDataType.DOUBLE, this, "");

    /**
     * The column
     * <code>ev_history.wallet_track_settlement_new.tariff_amount</code>.
     */
    public final TableField<WalletTrackSettlementNewRecord, Double> TARIFF_AMOUNT = createField(DSL.name("tariff_amount"), SQLDataType.DOUBLE, this, "");

    /**
     * The column
     * <code>ev_history.wallet_track_settlement_new.last_energy</code>.
     */
    public final TableField<WalletTrackSettlementNewRecord, Double> LAST_ENERGY = createField(DSL.name("last_energy"), SQLDataType.DOUBLE, this, "");

    /**
     * The column
     * <code>ev_history.wallet_track_settlement_new.wallet_amount</code>.
     */
    public final TableField<WalletTrackSettlementNewRecord, Double> WALLET_AMOUNT = createField(DSL.name("wallet_amount"), SQLDataType.DOUBLE, this, "");

    /**
     * The column
     * <code>ev_history.wallet_track_settlement_new.consumed_energy</code>.
     */
    public final TableField<WalletTrackSettlementNewRecord, Double> CONSUMED_ENERGY = createField(DSL.name("consumed_energy"), SQLDataType.DOUBLE, this, "");

    /**
     * The column
     * <code>ev_history.wallet_track_settlement_new.consumed_amount</code>.
     */
    public final TableField<WalletTrackSettlementNewRecord, Double> CONSUMED_AMOUNT = createField(DSL.name("consumed_amount"), SQLDataType.DOUBLE, this, "");

    /**
     * The column
     * <code>ev_history.wallet_track_settlement_new.total_consumed_amount</code>.
     */
    public final TableField<WalletTrackSettlementNewRecord, Double> TOTAL_CONSUMED_AMOUNT = createField(DSL.name("total_consumed_amount"), SQLDataType.DOUBLE, this, "");

    /**
     * The column
     * <code>ev_history.wallet_track_settlement_new.start_timestamp</code>.
     */
    public final TableField<WalletTrackSettlementNewRecord, DateTime> START_TIMESTAMP = createField(DSL.name("start_timestamp"), SQLDataType.TIMESTAMP(6), this, "", new DateTimeConverter());

    /**
     * The column
     * <code>ev_history.wallet_track_settlement_new.stop_timestamp</code>.
     */
    public final TableField<WalletTrackSettlementNewRecord, DateTime> STOP_TIMESTAMP = createField(DSL.name("stop_timestamp"), SQLDataType.TIMESTAMP(6), this, "", new DateTimeConverter());

    /**
     * The column
     * <code>ev_history.wallet_track_settlement_new.is_active_transaction</code>.
     */
    public final TableField<WalletTrackSettlementNewRecord, Boolean> IS_ACTIVE_TRANSACTION = createField(DSL.name("is_active_transaction"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column
     * <code>ev_history.wallet_track_settlement_new.dealer_unit_cost</code>.
     */
    public final TableField<WalletTrackSettlementNewRecord, Double> DEALER_UNIT_COST = createField(DSL.name("dealer_unit_cost"), SQLDataType.DOUBLE, this, "");

    /**
     * The column
     * <code>ev_history.wallet_track_settlement_new.dealer_total_amount</code>.
     */
    public final TableField<WalletTrackSettlementNewRecord, Double> DEALER_TOTAL_AMOUNT = createField(DSL.name("dealer_total_amount"), SQLDataType.DOUBLE, this, "");

    /**
     * The column
     * <code>ev_history.wallet_track_settlement_new.customer_share_amount</code>.
     */
    public final TableField<WalletTrackSettlementNewRecord, Double> CUSTOMER_SHARE_AMOUNT = createField(DSL.name("customer_share_amount"), SQLDataType.DOUBLE, this, "");

    /**
     * The column
     * <code>ev_history.wallet_track_settlement_new.total_share_amount</code>.
     */
    public final TableField<WalletTrackSettlementNewRecord, Double> TOTAL_SHARE_AMOUNT = createField(DSL.name("total_share_amount"), SQLDataType.DOUBLE, this, "");

    private WalletTrackSettlementNew(Name alias, Table<WalletTrackSettlementNewRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WalletTrackSettlementNew(Name alias, Table<WalletTrackSettlementNewRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ev_history.wallet_track_settlement_new</code>
     * table reference
     */
    public WalletTrackSettlementNew(String alias) {
        this(DSL.name(alias), WALLET_TRACK_SETTLEMENT_NEW);
    }

    /**
     * Create an aliased <code>ev_history.wallet_track_settlement_new</code>
     * table reference
     */
    public WalletTrackSettlementNew(Name alias) {
        this(alias, WALLET_TRACK_SETTLEMENT_NEW);
    }

    /**
     * Create a <code>ev_history.wallet_track_settlement_new</code> table
     * reference
     */
    public WalletTrackSettlementNew() {
        this(DSL.name("wallet_track_settlement_new"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : EvHistory.EV_HISTORY;
    }

    @Override
    public Identity<WalletTrackSettlementNewRecord, Integer> getIdentity() {
        return (Identity<WalletTrackSettlementNewRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<WalletTrackSettlementNewRecord> getPrimaryKey() {
        return Keys.KEY_WALLET_TRACK_SETTLEMENT_NEW_PRIMARY;
    }

    @Override
    public WalletTrackSettlementNew as(String alias) {
        return new WalletTrackSettlementNew(DSL.name(alias), this);
    }

    @Override
    public WalletTrackSettlementNew as(Name alias) {
        return new WalletTrackSettlementNew(alias, this);
    }

    @Override
    public WalletTrackSettlementNew as(Table<?> alias) {
        return new WalletTrackSettlementNew(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WalletTrackSettlementNew rename(String name) {
        return new WalletTrackSettlementNew(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WalletTrackSettlementNew rename(Name name) {
        return new WalletTrackSettlementNew(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WalletTrackSettlementNew rename(Table<?> name) {
        return new WalletTrackSettlementNew(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WalletTrackSettlementNew where(Condition condition) {
        return new WalletTrackSettlementNew(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WalletTrackSettlementNew where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WalletTrackSettlementNew where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WalletTrackSettlementNew where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WalletTrackSettlementNew where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WalletTrackSettlementNew where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WalletTrackSettlementNew where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WalletTrackSettlementNew where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WalletTrackSettlementNew whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WalletTrackSettlementNew whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
